# -*- coding: utf-8 -*-
"""MobiusStrip.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qfIp1JUD-iHzYLC3qq_-kyVnv8jkFeGk
"""

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

class MobiusStrip:
    def __init__(self, R=1.0, w=0.2, n=4):
        self.R = R
        self.w = w
        self.n = n
        self.u, self.v = np.meshgrid(
            np.linspace(0, 2 * np.pi, n),
            np.linspace(-w / 2, w / 2, n)
        )
        self.x, self.y, self.z = self.compute_mesh()

    def compute_mesh(self):
        u = self.u
        v = self.v
        x = (self.R + v * np.cos(u / 2)) * np.cos(u)
        y = (self.R + v * np.cos(u / 2)) * np.sin(u)
        z = v * np.sin(u / 2)
        return x, y, z

    def surface_area(self):
        du = 2 * np.pi / (self.n - 1)
        dv = self.w / (self.n - 1)

        xu = - (self.R + self.v * np.cos(self.u / 2)) * np.sin(self.u) - \
             self.v * np.sin(self.u / 2) * 0.5 * np.cos(self.u)
        yu = (self.R + self.v * np.cos(self.u / 2)) * np.cos(self.u) - \
             self.v * np.sin(self.u / 2) * 0.5 * np.sin(self.u)
        zu = self.v * 0.5 * np.cos(self.u / 2)

        xv = np.cos(self.u / 2) * np.cos(self.u)
        yv = np.cos(self.u / 2) * np.sin(self.u)
        zv = np.sin(self.u / 2)

        cross_x = yu * zv - zu * yv
        cross_y = zu * xv - xu * zv
        cross_z = xu * yv - yu * xv

        dA = np.sqrt(cross_x**2 + cross_y**2 + cross_z**2)
        area = np.sum(dA) * du * dv
        return area

    def edge_length(self):
        u = np.linspace(0, 2 * np.pi, self.n)
        v = self.w / 2

        def param_curve(v_sign):
            x = (self.R + v_sign * np.cos(u / 2)) * np.cos(u)
            y = (self.R + v_sign * np.cos(u / 2)) * np.sin(u)
            z = v_sign * np.sin(u / 2)
            return x, y, z

        edge_lengths = []
        for sign in [-1, 1]:
            x, y, z = param_curve(sign * v)
            dx = np.diff(x)
            dy = np.diff(y)
            dz = np.diff(z)
            edge_len = np.sum(np.sqrt(dx**2 + dy**2 + dz**2))
            edge_lengths.append(edge_len)

        return sum(edge_lengths)

    def plot(self):
        fig = plt.figure(figsize=(8, 6))
        ax = fig.add_subplot(111, projection='3d')
        ax.plot_surface(self.x, self.y, self.z, cmap='Blues', edgecolor='k', linewidth=0.1)
        ax.set_title("Mobius Strip")
        ax.set_xlabel("X")
        ax.set_ylabel("Y")
        ax.set_zlabel("Z")
        plt.tight_layout()
        plt.show()

if __name__ == "__main__":
    mobius = MobiusStrip(R=1, w=0.3, n=500)
    print(f"Surface Area ≈ {mobius.surface_area():.4f}")
    print(f"Edge Length ≈ {mobius.edge_length():.4f}")
    mobius.plot()